# Generated by Django 2.2.2 on 2020-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='1995-10-1', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='第一次登陆', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
    ]
